apiVersion: v1
kind: Pod
metadata:
  name: ubuntu
  labels:
          app: ubuntu
spec:
  containers:
  - image: ubuntu
    command:
      - "sleep"
      - "5"
    imagePullPolicy: IfNotPresent
    name: ubuntu
