apiVersion: v1
kind: Pod
metadata:
  name: mysqlserver
  labels:
          app: ubuntu
spec:
  containers:
  - image: mysql:5.6
    name: mysql
    env:
    - name: MYSQL_ROOT_PASSWORD
      value: mysecret
    ports:
    - containerPort: 3306
      name: mysql
