# pour tester ce projet 
# kubectl get pods -o wide 
# minikube ssh
# puis 
# curl http://IP/   ou IP est l'adresse ip du pod

apiVersion: v1
kind: Pod
metadata:
  name: phpmyadmin
  labels:
          app: front
spec:
  containers:
  - name: phpmyadmin
    image: phpmyadmin/phpmyadmin
    ports:
     - containerPort: 80
    env:
      - name: PMA_HOST
        value: "172.17.0.6"   ## pour l'instant, on recupere l'IP statiquement
      - name: PMA_PORT
        value: "3306"
      - name: MYSQL_ROOT_PASSWORD
        value: "mysecret"
     
