apiVersion: v1
kind: Service
metadata:
  name: phpmyadmin-service
  labels:
    app: frontend
spec:
  ports:
    - port: 80
  selector:
    app: frontend
  type: NodePort


### pour tester ce fichier : curl $(minikube service --url phpmyadmin-service)
