apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv2
  labels:
    name: mynfs # name can be anything
spec:
  storageClassName: manual # same storage class as pvc
  capacity:
    storage: 200Mi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 192.168.49.1       # ip addres of nfs server
    path: "/srv/nfsshare/data"  # path to directory
